name: hospital-dashboard
region: nyc
services:
  # Backend API Service
  - name: api
    github:
      repo: Oskwame/hospital-appointment-booking
      branch: main
      deploy_on_push: true
    source_dir: backend
    build_command: npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 8080
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        type: SECRET
      - key: JWT_SECRET
        type: SECRET
      - key: CLIENT_URL
        scope: RUN_TIME
      - key: CLOUDINARY_CLOUD_NAME
        type: SECRET
      - key: CLOUDINARY_API_KEY
        type: SECRET
      - key: CLOUDINARY_API_SECRET
        type: SECRET
  # Frontend Next.js Service
  - name: web
    github:
      repo: Oskwame/hospital-appointment-booking
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 3000
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: "${api.PUBLIC_URL}/api"
